name: MyResidence
version: ${project.version}
website: http://www.github.com/hohl/MyResidence

main: at.co.hohl.myresidence.bukkit.MyResidencePlugin
database: true

commands:
    residence:
        aliases: [res]
        description: Manage your residences.
        usage: /<command> <arguments...>
    town:
        description: Manage your town.
        usage: /<command> <arguments...>
    task:
        description: Confirm or canceling tasks.
        usage: /<command> confirm|cancel
    myresidence:
        aliases: [myres]
        description: Used to manage the MyResidence plugin.
        usage: /<command> <arguments...>
    map:
        description: Displays the town map.
        usage: /<command>
    home:
        description: Teleports you to the nearest home.
        usage: /<command>
    sethome:
        description: Sets the home point for the residence.
        usage: /<command>