name: MyResidence
main: at.co.hohl.myresidence.bukkit.MyResidencePlugin
version: "${project.version}"
database: true
commands:
    residence:
        aliases: [res]
        description: Manage your residences.
        usage: /<command> <arguments...>
    town:
        description: Manage your town.
        usage: /<command> <arguments...>
    task:
        description: Confirm or canceling tasks.
        usage: /<command> confirm|cancel
    myresidence:
        aliases: [myres]
        description: Used to manage the MyResidence plugin.
        usage: /<command> <arguments...>